name: device_calendar_example
description: Demonstrates how to use the device_calendar plugin.
version: 3.2.0
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  collection: ^1.17.2
  device_calendar:
    path: ../
  flutter:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  intl: ^0.17.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
